name: clima
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  geolocator: ^7.7.1
  http: ^0.13.4
  flutter_spinkit: ^5.1.0
  font_awesome_flutter: ^9.2.0
  intl: ^0.17.0
  shared_preferences: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
  - images/

  fonts:
  - family: Spartan MB
    fonts:
    - asset: fonts/SpartanMB-Black.otf
      weight: 900

  - family: Nunito
    fonts:
    - asset: fonts/Nunito-Regular.ttf

  - family: Cabin
    fonts:
    - asset: fonts/Cabin-Bold.ttf